version: "3.8"
services:
  servis-app:
    build:
      context: ./app
      target: builder
    image: denizlibsb_app
    ports:
      # The HTTP port
      - "80:8080"
    expose:
      - "8080"
    environment:
      - ENV=dev
    volumes:
      - ./app:/go/src/app
    # have to use $$ (double-dollar) so docker doesn't try to substitute a variable
    command: "go run ./"